fix: semantic dependency upload issue
eclipse-tractusx/sldt-semantic-hub pull request #309
Opened 2024-12-18 13:20 UTC by mittalVaghela

## Description
Bug Fix:  fix semantic dependent model upload issue

### Following changes :
- Update SAMM SDK Version to 2.9.8
- Update Jena Server to 5.0.0 
- Update common-io version 2.17
- Update the validation logic according to new version
- Remove Unwanted code
- Added test case for samm dependent model validation 

## Issue:
Fixes #237

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-12-18 14:26 UTC, agg3fe commented
@mittalVaghela Thanks for the updates.
IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases
It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. 
Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it.
FYI @tunacicek @jSchuetz88

2024-12-20 05:08 UTC, mittalVaghela commented
> @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88

@Sahin


> @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88

@agg3fe Thank you for your suggestion. I will update it to the latest version, 2.9.7, and let you know once it's ready for final review.

2024-12-20 06:22 UTC, mittalVaghela commented
> > @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88
> 
> @agg3fe Thank you for your suggestion. I will update it to the latest version, 2.9.7, and let you know once it's ready for final review.

@agg3fe  i have updated the SAMM SDK to the latest version of ESMF (2.9.7) and Jena (5.0.0). Could you please verify this again?

2025-01-14 09:32 UTC, tunacicek requested changes

2025-01-14 09:32 UTC, tunacicek commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java
> -         if(!isBamm()){
This check is removed- Do we not need to load the namespaces for bamm?

2025-01-14 09:32 UTC, tunacicek commented on backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
> +	 //issue its fix into latest jena version 4.9.0 or above
Why are the following tests disabled?

2025-01-14 09:32 UTC, tunacicek commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java
> +       final JsonSchemaGenerationConfig config = JsonSchemaGenerationConfigBuilder.builder()
Does it make sense to create this object one time on class init?

2025-01-14 09:32 UTC, tunacicek commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java
> +			final DocumentationGenerationConfig config = DocumentationGenerationConfigBuilder.builder()
Also here: 
Does it make sense to create this object one time on class init?

2025-01-14 09:33 UTC, tunacicek commented
@mittalVaghela : thanks for the PR. 
Also the https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/README.md needs to be adjusted to describe jena 5.0.0

2025-01-14 09:33 UTC, tunacicek commented
@mittalVaghela : You need to accept the eca -> https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/sldt-semantic-hub/309

2025-01-15 10:19 UTC, mittalVaghela commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/TripleStoreConfiguration.java
> -                         .enableCors( true )
ok i will revert this changes.

2025-01-15 10:19 UTC, mittalVaghela commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java
> +	public Try<AspectModel> loadAspectModel(String modelUrn){
project inbuild

2025-01-15 10:19 UTC, mittalVaghela commented on backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
> +	 //issue its fix into latest jena version 4.9.0 or above
Actully latest version of jena and  samm sdk validator it will take it as warning not as error so i comment out this test case

2025-01-15 10:20 UTC, mittalVaghela commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java
> +			final DocumentationGenerationConfig config = DocumentationGenerationConfigBuilder.builder()
config object has single use only for this method i prefer to create this object when it will required.

2025-01-17 11:42 UTC, agg3fe commented
Hi @mittalVaghela, I just noticed one thing. The spring boot version in your local application is 3.2.4, but the latest spring boot version in tractusx repo is 3.2.5. There are some other dependencies also which are different in both pom.xml files. Could you please compare and update this in your repo and build the project again. Otherwise this might create some discrepancies in final build.
also this is important to create an IP issue for the new Restricted dependencies. That part I will handle as soon as pom.xml is updated.
Thanks

2025-01-17 12:05 UTC, mittalVaghela commented
> Hi @mittalVaghela, I just noticed one thing. The spring boot version in your local application is 3.2.4, but the latest spring boot version in tractusx repo is 3.2.5. There are some other dependencies also which are different in both pom.xml files. Could you please compare and update this in your repo and build the project again. Otherwise this might create some discrepancies in final build. also this is important to create an IP issue for the new Restricted dependencies. That part I will handle as soon as pom.xml is updated. Thanks

sure i will

2025-01-28 08:31 UTC, agg3fe commented
> @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.

Currently we are waiting for the approval of IP issue raised.

2025-01-28 08:55 UTC, mittalVaghela commented
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

ok. but i updated [chart](version: "0.4.3", path: "charts/semantic-hub"))

2025-01-28 08:56 UTC, mittalVaghela commented
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

ok.

2025-01-28 09:24 UTC, agg3fe commented on charts/semantic-hub/Chart.yaml
> +appVersion: 0.5.3
for now, remove changes to `appVersion` and keep only `version`. We will need to build a new version 0.5.3 after this PR is merged. will create a new PR for that.
Also please add changelog to this PR, stating the major changes this PR has.

2025-02-03 13:41 UTC, tunacicek commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java
> +	public Try<AspectModel> loadAspectModel( String modelUrn ){
Code Format not correct.

2025-02-03 13:50 UTC, tunacicek commented on backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java
> +	  validateStatusParameter(status);
code format not correct

2025-02-03 13:53 UTC, tunacicek commented on backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java
> +				    .andExpect( jsonPath( "$.error.details.validationError",
format?

2025-02-04 15:01 UTC, agg3fe commented
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

@mittalVaghela IP issue is closed now. As soon as you fix the comments, we can merge the PR.
Also please squash the commits before we can merge it.

2025-02-06 06:43 UTC, mittalVaghela commented
> > > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> > 
> > 
> > Currently we are waiting for the approval of IP issue raised.
> 
> @mittalVaghela IP issue is closed now. As soon as you fix the comments, we can merge the PR. Also please squash the commits before we can merge it.

@agg3fe & @tunacicek , I have addressed all the comments and implemented the suggested changes. Please review it again and let me know if any further changes are needed. Thank you!

2025-02-06 13:26 UTC, mittalVaghela reviewed
All changes its done

2025-02-06 14:43 UTC, agg3fe approved these changes
LGTM

2025-02-06 14:47 UTC, merged